spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=fredericmencier
spring.datasource.password=admin
spring.datasource.url=jdbc:postgresql://localhost:5432/jjvector

app.timer.fixed-delay=10000